//! LLM contract, validation, and repair helpers for crossword sessions.

use crate::errors::DomainError;
use crate::policies::CrosswordConfig;
use serde::{Deserialize, Serialize};

pub const CROSSWORD_LLM_SCHEMA_VERSION: u32 = 1;

// ── Hints-and-bridges LLM types (new strategy) ───────────────────────────────

pub const CROSSWORD_HINTS_SCHEMA_VERSION: u32 = 1;

/// One word + its short clue sentence as returned by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrosswordWordHint {
    pub word: String,
    pub hint: String,
}

/// What the LLM returns for the hints-and-bridges strategy.
/// The grid is built by the deterministic placer in `crossword_placer`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrosswordHintsLlmOutput {
    pub schema_version: u32,
    /// Short story using the hard words (kept for translation-hint and display).
    pub story: String,
    /// Hints for the caller-supplied hard words (may be a subset if LLM omits some).
    pub hard_word_hints: Vec<CrosswordWordHint>,
    /// Bridge / helper words generated by the LLM.
    pub bridge_words: Vec<CrosswordWordHint>,
}

/// Blocked cell marker in LLM `grid` rows (not playable).
pub const CROSSWORD_BLOCK: char = '#';

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CrosswordDirection {
    Across,
    Down,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrosswordWordEntry {
    pub id: u32,
    pub answer: String,
    pub hint: String,
    pub start_row: usize,
    pub start_col: usize,
    pub direction: CrosswordDirection,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrosswordLlmOutput {
    pub schema_version: u32,
    /// Inspired prose; also the **full-text translation** source (like gap-fill `full_text`).
    pub story: String,
    /// One string per row; each row is the same length. Letters are learner language characters;
    /// blocked squares use `#`.
    pub grid: Vec<String>,
    pub words: Vec<CrosswordWordEntry>,
}

impl CrosswordLlmOutput {
    pub fn grid_dims(&self) -> Result<(usize, usize), DomainError> {
        let rows = self.grid.len();
        if rows == 0 {
            return Err(DomainError::InvalidCrosswordContext("empty grid".into()));
        }
        let cols = self.grid[0].chars().count();
        if cols == 0 {
            return Err(DomainError::InvalidCrosswordContext(
                "grid row 0 empty".into(),
            ));
        }
        for (i, row) in self.grid.iter().enumerate() {
            if row.chars().count() != cols {
                return Err(DomainError::InvalidCrosswordContext(format!(
                    "grid row {i} width mismatch"
                )));
            }
        }
        Ok((rows, cols))
    }

    pub fn cell_char(&self, row: usize, col: usize) -> Result<char, DomainError> {
        let (rows, cols) = self.grid_dims()?;
        if row >= rows || col >= cols {
            return Err(DomainError::InvalidCrosswordContext(format!(
                "cell out of bounds ({row},{col})"
            )));
        }
        let line = &self.grid[row];
        let mut it = line.chars();
        let c = it.nth(col).ok_or_else(|| {
            DomainError::InvalidCrosswordContext(format!("missing char at ({row},{col})"))
        })?;
        Ok(c)
    }

    /// Uppercases all grid row strings and all word answers in-place.
    /// Call this after parsing LLM output so validation and cell-matching are case-consistent.
    pub fn normalize_case(&mut self) {
        self.grid = self
            .grid
            .iter()
            .map(|row| row.to_uppercase())
            .collect();
        for w in &mut self.words {
            w.answer = w.answer.to_uppercase();
        }
    }

    /// Makes all grid rows the same width by padding short rows with `#` on the right.
    /// Uses the maximum row width as the canonical width (LLMs tend to truncate rather than extend).
    /// Call this after `normalize_case` and before `validate`.
    pub fn repair_grid_widths(&mut self) {
        if self.grid.is_empty() {
            return;
        }
        let max_width = self.grid.iter().map(|r| r.chars().count()).max().unwrap_or(0);
        if max_width == 0 {
            return;
        }
        for row in &mut self.grid {
            let len = row.chars().count();
            if len < max_width {
                let padding: String = std::iter::repeat('#').take(max_width - len).collect();
                row.push_str(&padding);
            }
        }
    }

    /// Rewrites grid cells that are inconsistent with word entries.
    ///
    /// Two LLM error modes handled:
    /// 1. **Block overlap** — a word passes through a `#` cell. The word's letter is authoritative;
    ///    replace the `#` with the word's letter at that offset.
    /// 2. **Letter mismatch** — a word's letter at an offset differs from the grid cell. Again the
    ///    word answer is treated as authoritative and the grid cell is overwritten.
    ///
    /// If two *different* words disagree on the letter at a shared intersection cell, the first word
    /// (in order) wins. The resulting grid may still fail validation for the second word; in that case
    /// the retry loop in the LLM layer will fetch a fresh response.
    ///
    /// Call this after `repair_grid_widths`.
    pub fn repair_word_grid_conflicts(&mut self) {
        // Build a mutable char matrix so we can overwrite individual cells efficiently.
        let rows = self.grid.len();
        if rows == 0 {
            return;
        }
        let cols = self.grid[0].chars().count();
        if cols == 0 {
            return;
        }

        let mut matrix: Vec<Vec<char>> = self
            .grid
            .iter()
            .map(|row| row.chars().collect())
            .collect();

        for w in &self.words {
            let answer_chars: Vec<char> = w.answer.chars().collect();
            let n = answer_chars.len();
            for i in 0..n {
                let (r, c) = match w.direction {
                    CrosswordDirection::Across => (w.start_row, w.start_col + i),
                    CrosswordDirection::Down => (w.start_row + i, w.start_col),
                };
                if r >= rows || c >= cols {
                    // Out-of-bounds: can't repair, validation will reject.
                    continue;
                }
                let grid_ch = matrix[r][c];
                let word_ch = answer_chars[i];
                // Replace '#' blocks and wrong letters with the word's letter.
                if grid_ch == CROSSWORD_BLOCK || grid_ch != word_ch {
                    matrix[r][c] = word_ch;
                }
            }
        }

        // Write the repaired matrix back to grid strings.
        self.grid = matrix
            .into_iter()
            .map(|row| row.into_iter().collect())
            .collect();
    }

    /// Validates shape, story, word paths vs grid, and uniqueness of ids.
    pub fn validate(&self) -> Result<(), DomainError> {
        if self.schema_version != CROSSWORD_LLM_SCHEMA_VERSION {
            return Err(DomainError::InvalidCrosswordContext(format!(
                "schema_version want {CROSSWORD_LLM_SCHEMA_VERSION} got {}",
                self.schema_version
            )));
        }
        let story = self.story.trim();
        if story.is_empty() {
            return Err(DomainError::InvalidCrosswordContext(
                "story empty".into(),
            ));
        }
        let (rows, cols) = self.grid_dims()?;
        if self.words.is_empty() {
            return Err(DomainError::InvalidCrosswordContext(
                "no words".into(),
            ));
        }
        let mut seen_ids = std::collections::HashSet::new();
        for w in &self.words {
            if !seen_ids.insert(w.id) {
                return Err(DomainError::InvalidCrosswordContext(format!(
                    "duplicate word id {}",
                    w.id
                )));
            }
            let hint = w.hint.trim();
            if hint.is_empty() {
                return Err(DomainError::InvalidCrosswordContext(format!(
                    "empty hint for word id {}",
                    w.id
                )));
            }
            let ans = w.answer.trim();
            if ans.is_empty() {
                return Err(DomainError::InvalidCrosswordContext(format!(
                    "empty answer for word id {}",
                    w.id
                )));
            }
            if ans.chars().any(|c| c == CROSSWORD_BLOCK) {
                return Err(DomainError::InvalidCrosswordContext(format!(
                    "answer for id {} must not contain block marker",
                    w.id
                )));
            }
            let len = ans.chars().count();
            if len == 0 {
                continue;
            }
            match w.direction {
                CrosswordDirection::Across => {
                    if w.start_col + len > cols || w.start_row >= rows {
                        return Err(DomainError::InvalidCrosswordContext(format!(
                            "across word id {} out of bounds",
                            w.id
                        )));
                    }
                    for (i, ch) in ans.chars().enumerate() {
                        let gc = self.cell_char(w.start_row, w.start_col + i)?;
                        if gc == CROSSWORD_BLOCK {
                            return Err(DomainError::InvalidCrosswordContext(format!(
                                "across word id {} overlaps block",
                                w.id
                            )));
                        }
                        if gc != ch {
                            return Err(DomainError::InvalidCrosswordContext(format!(
                                "across word id {} grid mismatch at offset {i}",
                                w.id
                            )));
                        }
                    }
                }
                CrosswordDirection::Down => {
                    if w.start_row + len > rows || w.start_col >= cols {
                        return Err(DomainError::InvalidCrosswordContext(format!(
                            "down word id {} out of bounds",
                            w.id
                        )));
                    }
                    for (i, ch) in ans.chars().enumerate() {
                        let gc = self.cell_char(w.start_row + i, w.start_col)?;
                        if gc == CROSSWORD_BLOCK {
                            return Err(DomainError::InvalidCrosswordContext(format!(
                                "down word id {} overlaps block",
                                w.id
                            )));
                        }
                        if gc != ch {
                            return Err(DomainError::InvalidCrosswordContext(format!(
                                "down word id {} grid mismatch at offset {i}",
                                w.id
                            )));
                        }
                    }
                }
            }
        }
        Ok(())
    }

    pub fn validate_against_crossword_config(&self, cfg: &CrosswordConfig) -> Result<(), DomainError> {
        self.validate()?;
        let (rows, cols) = self.grid_dims()?;
        if rows > cfg.max_grid_rows as usize || cols > cfg.max_grid_cols as usize {
            return Err(DomainError::InvalidCrosswordContext(format!(
                "grid size {rows}x{cols} exceeds max {}x{}",
                cfg.max_grid_rows, cfg.max_grid_cols
            )));
        }
        if self.words.len() > cfg.max_words as usize {
            return Err(DomainError::InvalidCrosswordContext(format!(
                "words count {} exceeds max_words {}",
                self.words.len(),
                cfg.max_words
            )));
        }
        for w in &self.words {
            if w.hint.chars().count() > cfg.max_hint_chars as usize {
                return Err(DomainError::InvalidCrosswordContext(format!(
                    "hint for word id {} too long",
                    w.id
                )));
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tiny_valid() -> CrosswordLlmOutput {
        CrosswordLlmOutput {
            schema_version: CROSSWORD_LLM_SCHEMA_VERSION,
            story: "A cat sat.".into(),
            grid: vec!["CAT".into(), "#A#".into(), "DOG".into()],
            words: vec![
                CrosswordWordEntry {
                    id: 0,
                    answer: "CAT".into(),
                    hint: "An animal".into(),
                    start_row: 0,
                    start_col: 0,
                    direction: CrosswordDirection::Across,
                },
                CrosswordWordEntry {
                    id: 1,
                    answer: "DOG".into(),
                    hint: "Another animal".into(),
                    start_row: 2,
                    start_col: 0,
                    direction: CrosswordDirection::Across,
                },
            ],
        }
    }

    #[test]
    fn validate_ok() {
        tiny_valid().validate().unwrap();
    }

    #[test]
    fn validate_rejects_mismatch() {
        let mut x = tiny_valid();
        x.words[0].answer = "CAR".into();
        assert!(x.validate().is_err());
    }
}
